# Generated by Django 2.1.7 on 2019-06-26 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190627_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=0, max_digits=13)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Branches',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Branches'),
        ),
        migrations.AddField(
            model_name='courses',
            name='Contacts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Contacts'),
        ),
    ]
