# Generated by Django 2.1.7 on 2019-06-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190628_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='value',
            field=models.CharField(max_length=80),
        ),
    ]
