# Generated by Django 2.1.7 on 2019-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190628_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='value',
            field=models.CharField(max_length=512),
        ),
    ]
