# Generated by Django 2.1.7 on 2019-06-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190628_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Branches',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Contacts',
        ),
        migrations.AddField(
            model_name='branches',
            name='cours',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='cours',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
