# Generated by Django 2.1.7 on 2019-06-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190628_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.DeleteModel(
            name='ContactsType',
        ),
    ]
