# Generated by Django 2.1.7 on 2019-07-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190711_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('imgpath', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='cours',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.Courses'),
        ),
    ]
