# Generated by Django 2.1.7 on 2019-07-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20190711_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cours',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.Courses'),
        ),
    ]
