# Generated by Django 2.2.2 on 2019-07-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190711_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='discription',
            new_name='description',
        ),
    ]
