# Generated by Django 2.2.2 on 2019-07-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190716_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='description',
            new_name='discription',
        ),
    ]
